name: Build and Release R Package

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      release_name:
        description: 'Release name'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Setup R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: rmarkdown

    - name: Build package
      run: |
        R CMD build .
        R CMD INSTALL --build .
      shell: bash

    - name: Extract version (Linux and macOS)
      if: runner.os != 'Windows'
      id: get_version_unix
      run: |
        version=$(grep -m1 '^Version:' DESCRIPTION | awk '{print $2}')
        echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV

    - name: Extract version (Windows)
      if: runner.os == 'Windows'
      id: get_version_windows
      run: |
        $version = (Get-Content DESCRIPTION | Select-String -Pattern '^Version:' | ForEach-Object { $_.Line.Split(' ')[1] }).Trim()
        echo "PACKAGE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: r-package-${{ matrix.os }}
        path: '*.tar.gz' # or '*.zip' for Windows binaries

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifacts (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/download-artifact@v2
      with:
        name: r-package-ubuntu-latest
        path: binaries/ubuntu

    - name: Download artifacts (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/download-artifact@v2
      with:
        name: r-package-windows-latest
        path: binaries/windows

    - name: Download artifacts (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/download-artifact@v2
      with:
        name: r-package-macos-latest
        path: binaries/macos

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: binaries/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
