name: Build and Release R Package

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      release_name:
        description: 'Release name'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install remotes package
      run: |
        Rscript -e 'install.packages("remotes")'

    - name: Install dependencies
      run: |
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'

    - name: Build package
      run: |
        R CMD build .
        R CMD INSTALL --build .
      shell: bash

    - name: Extract version (Linux/Mac)
      if: runner.os != 'Windows'
      id: get_version
      run: |
        version=$(grep -m1 '^Version:' DESCRIPTION | awk '{print $2}')
        echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV

    - name: Extract version (Windows)
      if: runner.os == 'Windows'
      id: get_version
      run: |
        $version = (Get-Content DESCRIPTION | Select-String -Pattern '^Version:' | ForEach-Object { $_.Line.Split(' ')[1] }).Trim()
        echo "PACKAGE_VERSION=$version" >> $env:GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: r-package-${{ matrix.os }}
        path: '*.tar.gz' # or '*.zip' for Windows binaries

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: r-package-ubuntu-latest
        path: binaries/ubuntu

    - uses: actions/download-artifact@v2
      with:
        name: r-package-windows-latest
        path: binaries/windows

    - uses: actions/download-artifact@v2
      with:
        name: r-package-macos-latest
        path: binaries/macos

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        release_name: osmdata_${{ env.PACKAGE_VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (Ubuntu)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: binaries/ubuntu/*.tar.gz
        asset_name: osmdata_${{ env.PACKAGE_VERSION }}_ubuntu.tar.gz
        asset_content_type: application/gzip

    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: binaries/windows/*.zip
        asset_name: osmdata_${{ env.PACKAGE_VERSION }}_windows.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (macOS)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: binaries/macos/*.tar.gz
        asset_name: osmdata_${{ env.PACKAGE_VERSION }}_macos.tar.gz
        asset_content_type: application/gzip
